# Generated by Django 6.0.5 on 2026-06-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0005_alter_postagem_publicado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
