# Generated by Django 6.0.5 on 2026-07-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0006_postagem_disponivel_postagem_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='cor_fundo',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='postagem',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
