# Generated by Django 5.2.8 on 2026-01-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_noticia_imagem_alter_noticia_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='automatizado',
            new_name='automatizada',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='disponivel',
            new_name='em_display',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='sumario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='corpo',
            field=models.CharField(max_length=324),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='noticia',
            table='noticia',
        ),
        migrations.AlterModelTable(
            name='postagem',
            table='postagem',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
