# Generated by Django 6.0.5 on 2026-06-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_noticia_publicado_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='sumario',
            new_name='corpo',
        ),
    ]
